# Generated by Django 3.1 on 2020-09-11 05:54

from django.db import migrations, models
import usercontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0004_auto_20200911_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default.png', upload_to=usercontrol.models.Account.path_and_rename),
        ),
    ]
