# Generated by Django 3.1 on 2020-08-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_version_tutorial_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='tutorial_published',
            new_name='version_published',
        ),
    ]
