# Generated by Django 3.1 on 2020-08-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200811_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_published',
            new_name='version_published_date',
        ),
    ]
