# Generated by Django 3.1 on 2020-08-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200811_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='version_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_numbers', to='backend.version'),
        ),
    ]
