# Generated by Django 3.1 on 2020-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200811_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_published_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
