# Generated by Django 3.1 on 2020-08-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200811_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.FloatField(default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('version_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='backend.version')),
            ],
        ),
    ]
