# Generated by Django 3.1 on 2020-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200812_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_title', models.CharField(max_length=50)),
                ('helper_description', models.TextField()),
            ],
        ),
    ]
