# Generated by Django 3.1 on 2020-08-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_helper_helper_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='helper_open',
        ),
    ]
