# Generated by Django 3.1 on 2020-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='for_community',
            field=models.BooleanField(default=True),
        ),
    ]
