# Generated by Django 3.1 on 2020-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=500, unique=True),
        ),
    ]
