# Generated by Django 3.1 on 2020-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200820_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_content',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
