# Generated by Django 3.1 on 2020-08-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_topic_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
