# Generated by Django 3.1 on 2020-08-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='proudct_type',
            new_name='product_type',
        ),
    ]
